version: "3"
services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    image: tomcat:9
    volumes:
      - ../build/libs:/usr/local/tomcat/webapps
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "5005:5005"

volumes:
  mysql_data:
    external: true